# Generated by Django 4.2.7 on 2024-03-03 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kondicionery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table='category',
        ),
    ]
