# Generated by Django 4.2.7 on 2024-03-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kondicionery', '0003_products_imgmore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='imgmore',
            field=models.FileField(blank=True, null=True, upload_to='descpript_images', verbose_name='Изображение под описание'),
        ),
    ]
