# Generated by Django 4.2.7 on 2024-03-05 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kondicionery', '0005_alter_products_category_alter_products_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compressor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Компрессор',
                'verbose_name_plural': 'Компрессоры',
                'db_table': 'compress',
            },
        ),
        migrations.RemoveField(
            model_name='products',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='products',
            name='cooled',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Охлаждение'),
        ),
        migrations.AddField(
            model_name='products',
            name='heater',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Обогрев'),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Скидка в процентах'),
        ),
        migrations.DeleteModel(
            name='SubCategories',
        ),
        migrations.AddField(
            model_name='products',
            name='compress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='kondicionery.compressor', verbose_name='Компрессор'),
            preserve_default=False,
        ),
    ]
