# Generated by Django 4.2.7 on 2024-03-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kondicionery', '0006_compressor_remove_products_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='articul',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='products',
            name='cooled',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Охлаждение'),
        ),
        migrations.AlterField(
            model_name='products',
            name='heater',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Обогрев'),
        ),
    ]
