# Generated by Django 4.2.7 on 2024-03-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kondicionery', '0007_products_articul_alter_products_cooled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='square',
            field=models.IntegerField(default=0, verbose_name='Площадь охлаждения'),
        ),
    ]
