# Generated by Django 4.2.7 on 2024-03-06 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kondicionery', '0008_products_square'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
