# Generated by Django 4.2.7 on 2024-03-06 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventilyacia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='CategoriesVent',
        ),
    ]
