# Generated by Django 4.2.7 on 2024-03-07 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbar',
            options={'verbose_name': 'Навигацию', 'verbose_name_plural': 'Навигация'},
        ),
    ]
