# Generated by Django 4.2.7 on 2024-03-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_navbar_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='code',
            field=models.TextField(blank=True, null=True, verbose_name='code'),
        ),
    ]
