# Generated by Django 4.2.7 on 2024-03-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_navbar_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Титульник'),
        ),
    ]
