# Generated by Django 4.2.7 on 2024-03-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_navbar_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Титульник'),
        ),
    ]
